### ISSUE TITLE
Entry point

### ISSUE THREAD

**Issue by ahmadadiga** [orig74/UE4PyServer#2]
Hey

I have question regarding the installation of your plugins.

What do you mean by \<your entry point?

**Comment by orig74** [comment]
Hi,
you can see the documentation when you run:

> python config.py -h

usage: config.py [-h] [--entry_point ENTRY_POINT] [--entry_path ENTRY_PATH]

optional arguments:
  -h, --help            show this help message and exit
  --entry_point ENTRY_POINT
                        sets the module where main_loop function exists if the
                        entrypoint file does not exists it is created with the
                        functions main_loop and kill
  --entry_path ENTRY_PATH
                        a path where the entry_point exists

you can look at the [track_test.py](https://github.com/orig74/UE4PyServer/blob/master/Source/PyServer/Private/track_test.py) example, it has a main_loop function, and to tell the plugin how where to find the main_loop you run:

python config.py --entry_point track_test --entry_path [path to the file]
hope it's clear now.
